#ifndef GBUFFER_SLANGH
#define GBUFFER_SLANGH

[[vk::binding(0, 1)]] Texture2D GBufferA;
[[vk::binding(1, 1)]] Texture2D GBufferB;
[[vk::binding(2, 1)]] Texture2D GBufferC;
[[vk::binding(3, 1)]] Texture2D DepthBuffer;
[[vk::binding(4, 1)]] Texture2D PrevGBufferA;
[[vk::binding(5, 1)]] Texture2D PrevGBufferB;
[[vk::binding(6, 1)]] Texture2D PrevGBufferC;
[[vk::binding(7, 1)]] Texture2D PrevDepthBuffer;

#endif